name: carbon
description: A starting point for Dart libraries or applications.
version: 0.1.0
# repository: https://github.com/my_org/my_repo
resolution: workspace
environment:
  sdk: ">=3.9.2 <4.0.0"

publish_to: none

# Add regular dependencies here.
dependencies:
  clock: ^1.1.2
  intl: ^0.20.2
  meta: ^1.17.0
  time_machine2: ^0.13.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.28.0
