name: carbon
description: A starting point for Dart libraries or applications.
version: 0.1.0
# repository: https://github.com/my_org/my_repo
resolution: workspace
environment:
  sdk: '>=3.9.2 <4.0.0'

# Add regular dependencies here.
dependencies:
  clock: ^1.1.2
  intl: ^0.20.2
  timeago: ^3.7.1
  time_machine: ^0.9.17

dev_dependencies:
  lints: ^6.0.0
  test: ^1.28.0